name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  setup-and-checks:
    name: Install, Lint, Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint
        # if lint command returns non-zero, job will fail and show which files failed

      - name: Run tests (Jest)
        # adjust test command if your project uses Mocha/Jasmine/other
        run: |
          mkdir -p test-reports
          npm test -- --reporters=default --reporters=jest-junit || true
        env:
          CI: true

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            junit.xml
            test-reports/**/*.xml
            coverage
