name: Generate Release Notes

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., v1.0.1)"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate changelog file
        run: |
          VERSION=${{ github.event.inputs.version }}
          echo "# Release $VERSION" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "## Recent Commits" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          git log -n 10 --pretty=format:"- %s" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "Generated on $(date)" >> CHANGELOG.md

      - name: Display changelog
        run: cat CHANGELOG.md

      - name: Upload changelog as artifact
        uses: actions/upload-artifact@v4
        with:
          name: CHANGELOG
          path: CHANGELOG.md

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
